### ISSUE TITLE
node covered by 2 triangles exception

### ISSUE THREAD

**Issue by maorp** [mkazhdan/TextureSignalProcessing#11]
hi, I'm getting: [EXCEPTION] InitializeGridChartsActiveNodes: Node ( 662 , 344 ) covered by two triangles: 6567 6536
checked the 2 specific triangles UV coords and they look ok - they are not mapped to the same area. just to make sure - do the ids in the exception relate to the original input face indices?
I'm attaching data. thanks for any help.
[test1104_orig.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6305059/test1104_orig.zip)

**Comment by mkazhdan** [comment]
I believe that the problem is that both triangles share vertex 22821.
However, they are not in the same chart. That is, they cannot be connected through a sequence of shared edges. (Specifically, the two nodes corresponding to the triangles in the dual graph are not connected.)

**Comment by maorp** [comment]
thanks for the quick response!
checked verts for faces 6567 and 6536, i get different indices from you, they share an edge and it happens when InitializeGridChartsActiveNodes process the same chart (as identified internally in the function before in buildAtlasMesh)
verts 6567:  17398       24459       10427
verts 6536:  10427       15403       17398
how do you debug the mesh manifoldness and charting? do you have a tool i can use?

**Comment by mkazhdan** [comment]
Can you confirm that? I'm reading Mesh.ply and am getting:
triangle[6567] = ( 24458 , 11445 , 22821 )
triangle[6536] = ( 22821 , 28398 , 22535 )

Though visualizing the connected components is tricky, you can try opening the file Mesh.ply in MeshLab and then selecting
     Filters -> Selection -> Conditional Face Selection
and then specifying
     (fi == 6536) || (fi==6567)
That should highlight two triangles on the upper/outer left leg. You can see that they share a vertex, but it does look like there is something funny going on there.

**Comment by maorp** [comment]
had a weird bug reading the mesh... 
anyway the mesh needs repairing. does it have to be watertight?
thanks for the help and for the amazing algo.

**Comment by mkazhdan** [comment]
That's a good question. I think the method will work work if the mesh is not water-tight. However, it is not explicitly enforcing either Dirichlet or Neumann boundary conditions.

**Comment by maorp** [comment]
I'm checking with a high poly mesh without bad faces and get another exception:
Hierarchy structure =  3.6620
Hierarchy prolongation and restriction =  3.2210
Boundary coefficient initialization =  0.9870
Hierarchy construction =  7.8710
[EXCEPTION] LoopVertices: Non-simple loop, node 61297773248511

seems to happen when accumulating one of the charts boundary 
attached data.
[mask.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6319094/mask.zip)

**Comment by maorp** [comment]
oh i saw the closed issue with an explanation on non loop. ill go thru it.

**Comment by maorp** [comment]
Hi, checked the problematic chart, I cant see any non simple loop (triangles that meet at one vertex). plotted the atlas in wireframe and checked manually the boundary for badness. here is a zoom on the first chart (first large connected comp from above, "shoe sole"), it happens immediately on the first. attached the data again. 
![shoeChart](https://user-images.githubusercontent.com/11231999/115211097-e98b5e00-a107-11eb-8cdd-87a14cec8464.png)
![shoeChartZoom](https://user-images.githubusercontent.com/11231999/115211107-ec864e80-a107-11eb-9555-030aa0ed0b5f.png)
[mask.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6334704/mask.zip)

**Comment by mkazhdan** [comment]
While I got this message via email, I cannot seem to find it on GitHub.

Has it been resolved?

 

-- Misha

**Comment by maorp** [comment]
yes. had problems with my old atlas (charts with holes). moved to use UVAtlas and now it works. I have another interesting issue, but maybe its because I'm doing something hacky...  my mask has only 3 values - essentially all charts are the same source (white value) with some black holes for occluded areas and gray for the background. I get strong gradients on some seams. see the hand. 
[test210421_orig.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6353435/test210421_orig.zip)
attached data if you want to take a look. sometimes playing with the interpolation value (set to 1000) helps in this seam but blends bad color into other areas.
![image](https://user-images.githubusercontent.com/11231999/115609200-eb177a80-a2ef-11eb-97c5-649d98d994aa.png)

**Comment by maorp** [comment]
Hi, to clarify a bit the previous comment - I'm essentially trying to do only inpainting. is there another, less hacky way to do it?

**Comment by maorp** [comment]
Hi, update - I tried also with a correct composite and with multi option (just to check my hack mask is not the problem) and still i get strong gradients on seams. attached data, composite and multi.
[masks.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6385810/masks.zip)
[texels00to08.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6385855/texels00to08.zip)
[texels09to15.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6385864/texels09to15.zip)
[Mesh210421.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6385825/Mesh210421.zip)
![image](https://user-images.githubusercontent.com/11231999/116270746-0965f600-a788-11eb-8e76-a5b99800ad39.png)
with seams visualized:
![image](https://user-images.githubusercontent.com/11231999/116270790-14b92180-a788-11eb-8e44-81fda8a917f3.png)

**Comment by mkazhdan** [comment]
I see. You're right, there definitely should not be a gradient along the seam. Let me try to look into it.

**Comment by mkazhdan** [comment]
![boundary](https://user-images.githubusercontent.com/10869989/116801348-1f9cea80-aad7-11eb-8967-54ea9f590350.png)
[Mesh210421.zip](https://github.com/mkazhdan/TextureSignalProcessing/files/6410746/Mesh210421.zip)
The problem is that the mesh you are providing is not water-tight.
As a visualization, I have included an image of your mesh, with boundary edges turned on.
As you can see the different charts correspond to different disconnected components of the mesh.
As a result, there is no stitching across the chart boundaries.
To fix this, you need to merge the patches along the seams. (Since texture coordinates are stored with faces, not vertices, this will not affect the texture-mapping.
You can do this, for example, by opening your mesh in MeshLab, select Filters -> Cleaning and Repairing -> Merge Close vertices, and specifying a very small percent threshold. (I believe I used 0.01%.)
I have attached the result I got out of MeshLab.
When I ran with that, there was no longer a seam. (Though I did have to use the --jitter parameter to avoid the problem with a singular matrix.)

**Comment by maorp** [comment]
Great! looks like UVAtlasTool duplicates vertices on the chart boundaries.
Thank you very much for taking the time to debug it. It works now even with the hacky mask.
