### ISSUE TITLE
A problem with the Executables.

### ISSUE THREAD

**Issue by ChisonShang** [mkazhdan/TextureSignalProcessing#3]
Dear Michael Misha Kazhdan,
I couldn't open your Gradient Doain Texture Processing Executables(both v1 and v2).
If I click the exe, a window will flash and there won't be any interactive viewer.
So could you tell me how to solve this problem? 
Thanks for any insight or help.

**Comment by mkazhdan** [comment]
You need to run the executable(s) from the command line and provide the input file (and possibly texture) using the "--in" parameter. (If you run from the command line with no arguments, you'll see the full list of parameters. Alternatively, you can find a detailed description on the project home page.)

**Comment by ChisonShang** [comment]
Thanks for your help. I have already read the source code and found the solution.
