### ISSUE TITLE
A Problem about the Texture stitching

### ISSUE THREAD

**Issue by LamboAventador** [mkazhdan/TextureSignalProcessing#4]
How can I  stitch the partial textures into a single texture like the reference paper do in Fig.16?
Which EXECUTABLE can make it? Thanks for helping

**Comment by mkazhdan** [comment]
We're still cleaning up that piece of code of code for release. It should be available in the next week or two.

**Comment by LamboAventador** [comment]
Alright, Thanks for your quick reply.

**Comment by mkazhdan** [comment]
Stitching code is now available.

**Comment by LamboAventador** [comment]
Thanks for your reminding ! @mkazhdan
