### ISSUE TITLE
compiling for linux (ubuntu)

### ISSUE THREAD

**Issue by SriGanesh130** [mkazhdan/TextureSignalProcessing#6]
How to install the repo in the ubuntu system.

**Comment by mkazhdan** [comment]
There is a Makefile that should work.
Typing "make" should create a library bin/Linux (I believe) that contains the executables.

**Comment by SriGanesh130** [comment]
fatal_error : Triangle.h No such file or directory
getting error in make file [INCLUDE = /usr/include/ -I ./../include/].

**Comment by mkazhdan** [comment]
Strange. When I type "grep Triangle.h *.* in the "Src" directory I don't get any hits. Who is including Triangle.h?

**Comment by SriGanesh130** [comment]
Thanks for the replay,  the error is just because of naming convention. I changed triangle.h to Triangle.h and it's successfully compiled.

**Comment by mkazhdan** [comment]
Oh. Sorry. I thought you were talking about a different repo.
